services:
  nginx:
    container_name: nginx
    image: nginx:1.0
    build: ./requeriments/nginx
    env_file:
      - .env
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    secrets:
      - nginx_crt
      - nginx_key

  mariadb:
    container_name: mariadb
    image: mariadb:1.0
    build: ./requeriments/mariadb
    env_file:
      - .env
    restart: always
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:

networks:
  inception:
    driver: bridge

secrets:
  nginx_crt:
    file: ../${NGINX_CERT_FILE}
  nginx_key:
    file: ../${NGINX_KEY_FILE}
  mariadb_root_password: