services:
  nginx:
    container_name: nginx
    build: ./requeriments/nginx
    image: nginx:mvidal-h1.0
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    restart: unless-stopped
    ports:
      - "$NGINX_PORT:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    secrets:
      - nginx_crt
      - nginx_key

  mariadb:
    container_name: mariadb
    build: ./requeriments/mariadb
    image: mariadb:mvidal-h1.0
    environment:
      WP_DATABASE: ${DB_NAME}
      WPDB_USER: ${WPDB_USER}
      WPDB_ROOT_USER: ${WPDB_ROOT_USER}
      WPDB_USER_PASSWORD_FILE: /run/secrets/wpdb_user_password
      WPDB_ROOT_PASSWORD_FILE: /run/secrets/wpdb_root_password
      MDB_ROOT_PASSWORD_FILE: /run/secrets/mdb_root_password
      MARIADB_LOG_CONSOLE: true # Para que los logs se vean en docker logs
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - wpdb_root_password
      - wpdb_user_password
      - mdb_root_password

  wordpress:
    container_name: wordpress
    image: wordpress:mvidal-h1.0
    build: ./requeriments/wordpress
    env_file:
      - .env
    environment:
      WPDB_USER_PASSWORD_FILE: /run/secrets/wpdb_user_password
      WPDB_ROOT_PASSWORD_FILE: /run/secrets/wpdb_root_password
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
      - redis # Nuevo servicio de Redis en Bonus
    secrets:
      - wpdb_user_password
      - wpdb_root_password
      - wp_user_password
      - wp_admin_password

  redis:
    container_name: redis
    build: ./requeriments/bonus/redis
    image: redis:mvidal-h1.0
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN_NAME}/data/mariadb #CAMBIAR en .env en la VM!!!
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN_NAME}/data/wordpress
      o: bind

  redis_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN_NAME}/data/redis
      o: bind

secrets:
  nginx_crt:
    file: ../${NGINX_CERT_FILE}
  nginx_key:
    file: ../${NGINX_KEY_FILE}
  wpdb_root_password:
    file: ../secrets/db_root_password.txt
  wpdb_user_password:
    file: ../secrets/db_password.txt
  mdb_root_password:
    file: ../secrets/mariadb_root_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt